name: pluto_grid
description: PlutoGrid is a dataGrid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 5.2.1
homepage: https://pluto.weblaze.dev
repository: https://github.com/luckyAF/pluto_grid

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  rxdart: 0.27.5
  collection: 1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.2.0
  #  build_runner: 2.3.0
  flutter_lints: 1.0.4

dependency_overrides:
  code_builder: 4.1.0
  analyzer: 4.1.0
